# fly.toml app configuration file generated for crimson-wave-1075 on 2023-06-15T23:24:15-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "crimson-wave-1075"
primary_region = "lax"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
